delete from COMPRA;
delete from VENDEDOR;
delete from COMPRADOR;
delete from PERSONA;
delete from VEHICULO;
delete from LINEA;
delete from MARCA;

DROP TABLE COMPRA CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE COMPRADOR CASCADE CONSTRAINTS;
DROP TABLE PERSONA CASCADE CONSTRAINTS;
DROP TABLE VEHICULO CASCADE CONSTRAINTS;
DROP TABLE LINEA CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;